### PR TITLE
No peer in the pool, add recently disconnected peer and keep retrying…

### PR DESCRIPTION
**Pull request by thelazier**
Note sure if this impact to other project using darkcore or not. For insight-api-dash, The only peer connected should keep reconnecting, IMO.

### CODE REVIEW

**Comment by UdjinM6** [comment]
Hmm... I haven't dive deep into code but I'm not sure about this - wouldn't that lead to infinite loop connecting/disconnecting this probably faulty peer?
Also I'm not sure if that's the right place - _pool_ array just keeps records about peers available to connect to. Actual connected peers are in _peers_ array afaik so I guess _if (this.pool.length)_ means "if we still have _additional_ peers available to connect to" and not "if we still have _connections_".

**Comment by thelazier** [comment]
Yes, this will lead to infinite loop of connecting/disconnecting. 
With insight-api-dash calling this darkcore, there is only 1 peer which is our own dash daemon. 
I agree that this may not be the right place. It is now just to make sure that if the dashd restarted, darkcore (by insight node) will keep reconnecting to dashd. Unless the insight node will need to be restarted in order to have live transactions updated from peer.
By the way, I'm not fully understand all the code as well, my assumption may be wrong , so please forgive me if I'm totally wrong and wasting your time...

**Comment by UdjinM6** [comment]
Np at all :)

I just think it's not the darkcore problem but api is the one that should be fixed actually. Check this out https://github.com/UdjinM6/insight-api-dash/commit/c86ee341314e53fff0407853495d462149f46406 :)

PS. closing this also

**Comment by thelazier** [comment]
Thank you so much :+1:

**Pull request closed without merging**
